[package]
name = "rsr"
version = "0.1.0"
authors = ["Arthur Woimb√©e <arthur.woimbee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
regex = "1.3.1"
walkdir = "2.2.9"
